In [5]:
import numpy as np
a = np.arange(10).reshape(2,5)
print(a)
print(np.shape(a))

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


In [3]:
b = np.arange(10).reshape(5,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [6]:
a.ndim

2

In [12]:
a1 = np.ones((1,2,3),dtype = int)
a1

array([[[1, 1, 1],
        [1, 1, 1]]])

In [13]:
np.shape(a1)

(1, 2, 3)

In [14]:
np.ndim(a1)

3

In [15]:
a2 = np.arange(6).reshape(1,2,3)
a2

array([[[0, 1, 2],
        [3, 4, 5]]])

In [18]:
a3 = np.arange(24).reshape(2,3,4)
a3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [19]:
type(a)
type(a1)

numpy.ndarray

In [20]:
print(type(a1))

<class 'numpy.ndarray'>
