In [1]:
def func_01(a,b):
    if a%b == 0:
        print('a is divided by b')
    else:
        print('a is not divided by b')

In [2]:
func_01(10,2)

a is divided by b


In [3]:
func_01(23,3)

a is not divided by b


In [7]:
x = 10
print(type(x))
y = 1000 **1000
print(type(y))

<class 'int'>
<class 'int'>


In [11]:
a = [[1,2],[2,3],[3,4]]
for i in a:
    print (i)
for i in range(len(a)):
    print(i)

[1, 2]
[2, 3]
[3, 4]
0
1
2


### Transpose matrix using zip and numpy

In [33]:
for i in a:
    print(i)
b = [[a[row][col] 
        for row in range(len(a))]
        for col in range(len(a[0]))]
print()
for row in b:
    print(row)
        

[1, 2]
[2, 3]
[3, 4]

[1, 2, 3]
[2, 3, 4]


In [34]:
m = [[1,2],[1,3],[1,4]]
for i in m:
    print(i)

[1, 2]
[1, 3]
[1, 4]


In [35]:
zip_m = zip(*m)
for i in zip_m:
    print(i)

(1, 1, 1)
(2, 3, 4)


In [36]:
zip_01 = [[1,2,3],[11,12,13],[21,22,23],[31,32,33]]
zip_02 = zip(*zip_01)
for i in zip_01:
    print(i)
for i in zip_02:
    print(i)

[1, 2, 3]
[11, 12, 13]
[21, 22, 23]
[31, 32, 33]
(1, 11, 21, 31)
(2, 12, 22, 32)
(3, 13, 23, 33)


In [39]:
print(m)
for i in m:
    print(i)
b = [[m[row][col] 
        for row in range(len(a))]
        for col in range(len(a[0]))]
for i in b:
    print(i)

[[1, 2], [1, 3], [1, 4]]
[1, 2]
[1, 3]
[1, 4]
[1, 1, 1]
[2, 3, 4]


In [47]:
import numpy as np
print(zip_01)
print('\n', np.transpose(zip_01))

[[1, 2, 3], [11, 12, 13], [21, 22, 23], [31, 32, 33]]

 [[ 1 11 21 31]
 [ 2 12 22 32]
 [ 3 13 23 33]]


In [55]:
a = 'local variable'
def gobal():
   global a
   a = 'Global varaible'
   print(a)
gobal()
print(a)

Global varaible
Global varaible


In [53]:
a = 'global variable'
def fun_02():
    a = 'Local variable'
    print(a)
fun_02()
print(a)

Local variable
global variable


In [56]:
def fun_03():
    global s
    print(s)
    s = 'Python programming'
    print(s)
s = 'Data science'
fun_03()
print(s)

Data science
Python programming
Python programming


### Packing

In [57]:
def func_04(x,y,z):
    print(x,y,z)
list_01 = [11,12,13]

In [59]:
func_04(list_01)

TypeError: func_04() missing 2 required positional arguments: 'y' and 'z'

### Unpacking

In [60]:
func_04(*list_01)

11 12 13


In [61]:
range(3,6)

range(3, 6)

In [75]:
def Sum(*a):
    sum = 0
    for i in range(0,len(a)):
        sum = sum + a[i]
    return sum

In [76]:
Sum(11,52,56)

119

In [82]:
def func_05(*a):
    a = list(a)
    count = 0
    for i in range(len(a)):        
        a[i] = count
        count += 1
    func_04(*a)

In [83]:
func_05(23,34,76)

0 1 2


In [84]:
def func1(x,y,z):
    print(x,y,z)
def func2(*args):
    args = list(args)
    args[0] = "I"
    args[1] = 'Love'
    func1(*args)

In [85]:
func2('Hello','World','INDIA')

I Love INDIA


In [90]:
s = '100'
i = int(s,2)
print(i)

4


In [96]:
x = '@'
y = ord(x)
print(y)

64


In [97]:
complex(2,87)

(2+87j)