NumPy (or Numpy) is a Linear Algebra Library for Python

Numpy is also incredibly fast, as it has bindings to C libraries.

Why NumPy:

http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists

In [1]:
import numpy as np

In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [5]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [23]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [24]:
np.ones((2,4),dtype=float)

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [9]:
np.random.randint(0,10)

6

In [13]:
arr = np.random.randint(0,100,10)

In [14]:
arr

array([65, 74, 84, 85, 36, 14, 61, 63,  0,  6])

In [15]:
arr.max()

85

In [16]:
arr.max()

85

In [17]:
arr.min()

0

In [18]:
arr.mean()

48.799999999999997

In [19]:
arr.reshape(2,5)

array([[65, 74, 84, 85, 36],
       [14, 61, 63,  0,  6]])

In [61]:
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [60]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [63]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

In [43]:
b = np.arange((16),dtype=float).reshape(4,4)

In [44]:
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [49]:
mat = np.arange(100).reshape(10,10)

In [50]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [55]:
mat.shape

(10, 10)

In [51]:
row = 0
col = 1

In [52]:
mat[row,col]

1

In [53]:
row = 1
col = 3

In [54]:
mat[row,col]

13

In [76]:
A = np.array([[1,1], [0,1]])

In [77]:
A

array([[1, 1],
       [0, 1]])

In [78]:
B = np.array( [[2,0],[3,4]])


In [79]:
B

array([[2, 0],
       [3, 4]])

In [80]:
A*B

array([[2, 0],
       [0, 4]])

In [81]:
A.dot(B) 

array([[5, 4],
       [3, 4]])

In [82]:
np.dot(A, B)  

array([[5, 4],
       [3, 4]])

In [84]:
b = np.random.random((2,3))

In [85]:
b

array([[ 0.96046534,  0.23457175,  0.88745843],
       [ 0.50452841,  0.98340698,  0.55340884]])

In [86]:
a *= 3

In [87]:
a

array([[ 3.,  3.,  3.],
       [ 3.,  3.,  3.]])

In [88]:
b += a

In [89]:
b

array([[ 3.96046534,  3.23457175,  3.88745843],
       [ 3.50452841,  3.98340698,  3.55340884]])

In [91]:
a = np.random.random((2,3))

In [64]:
a

array([[ 0.97155283,  0.07121623,  0.23722243],
       [ 0.41424979,  0.04383785,  0.24763077]])

In [90]:
a.sum()

18.0

In [92]:
a.min()

0.078567400555014433

In [93]:
a.max()

0.95447283984629405

In [3]:
b = np.arange(12).reshape(3,4)

In [4]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
# sum of each column
b.sum(axis=0) 


array([12, 15, 18, 21])

In [8]:
b.sum(axis=1) 

array([ 6, 22, 38])

In [9]:
b.min(axis=1)      

array([0, 4, 8])

In [94]:
b

array([[ 3.96046534,  3.23457175,  3.88745843],
       [ 3.50452841,  3.98340698,  3.55340884]])

In [95]:
b.T

array([[ 3.96046534,  3.50452841],
       [ 3.23457175,  3.98340698],
       [ 3.88745843,  3.55340884]])


#### Assignments
1.Create an array of 10 zeros 
2.Create an array of 10 ones
3.Create an array of the integers from 10 to 50
4.Create a 3x3 matrix with values ranging from 0 to 8
#### More learning resources


https://docs.scipy.org/doc/numpy-1.13.0/reference/

https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

https://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html